### ISSUE TITLE
Can you add "PlayerPoints" support? 👀

### ISSUE THREAD

**Issue by darealpaoo** [LMBishop/MoneyPouch#17]
I see Economies (https://github.com/LMBishop/MoneyPouch/wiki/Config#economies) didn't support for PlayerPoints so can you add it please? 😀

![image](https://user-images.githubusercontent.com/47385360/128391345-e8b6c225-62d6-4329-acd5-7e42911ca9f3.png)

PlayerPoints plugin: https://www.spigotmc.org/resources/playerpoints.80745/

Have a great day 🤗
(Sorry for my bad English if it makes you confusing)

**Comment by CloudeLecaw** [comment]
https://www.spigotmc.org/resources/moneypouchdeluxe.118795/
