### ISSUE TITLE
Duplicate money boxes endlessly

### ISSUE THREAD

**Issue by Blueeyestar** [LMBishop/MoneyPouch#2]
we have a big problem. We use MoneyPouch. if the users vote they get a vault box as a thank you. Now I have discovered when the votes are in the creative world and they also get the boxes and can multiply them as desired !!! can you create a permission that forbids using it in certain worlds?

**Comment by CloudeLecaw** [comment]
also effect XP boxes

**Comment by CloudeLecaw** [comment]
At the moment i asked an other dev to add useage permissions to it + Messaage when you dont have this Permission to use a Pouch.
It works perfect as we needed it and solved the problem for us.
So we are using this moddified Version for now of MoneyPouch.
If LMBishop is interested in it i can send him a copy. May he thinks about adding this or some stuff like this to the official MoneyPouch Version too :-)
