### ISSUE TITLE
Placeholderapi support for more "economytype"?

### ISSUE THREAD

**Issue by Reeferx7** [LMBishop/MoneyPouch#9]
Hello can you add support to placeholderapi placeholders with command type example:

    Token-1:
      name: "Tokens"
      item: "CHEST"
     command: tokens give player %amount%
      pricerange:
        from: 10
        to: 100
      options:
       economytype: "%placeholder_api_placeholder%"
      lore:
        - "&7Open this pouch to receive Tokens!"

Is tha possible to be done?

**Comment by CloudeLecaw** [comment]
I agree this new pouchtype would be nice :)

Well its more the part with the support to let a pouch
Execute a command (like a command from console). This would Minimum need placeholders for   player  and  amount.

Any..may  others too? ;)
With the support to execute commands, i think he could release the OTs idea with supporting his token economy too :)
